language: python
python:
 - "2.7"
env:
 - DJANGO_VERSION=1.4.15
 - DJANGO_VERSION=1.5.10
 - DJANGO_VERSION=1.6.7
 - DJANGO_VERSION=1.7
install:
 - pip install pep8 pyflakes coverage python-coveralls
 - python setup.py install
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION
script:
 - pep8 calaccess_raw
 - pyflakes calaccess_raw
 - coverage run example/manage.py test calaccess_raw
after_success:
 - coveralls
